# Generated by Django 3.0.7 on 2020-06-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_auto_20200609_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(max_length=250, verbose_name='Статус заказа')),
                ('status_bool', models.BooleanField(verbose_name='Выполнен?')),
                ('volume', models.IntegerField(default=0, verbose_name='Объем')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Fuel')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата взятия')),
                ('status_bool', models.BooleanField(verbose_name='Выполнен?')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cabinet.Order')),
            ],
        ),
    ]
