# Generated by Django 3.0.7 on 2020-06-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_getting',
            field=models.BooleanField(default=False, verbose_name='Привязан к сотруднику?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_bool',
            field=models.BooleanField(default=False, verbose_name='Выполнен?'),
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_client', models.FileField(blank=True, upload_to='client/docs/', verbose_name='Документы клиента')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('juristical_address', models.TextField(blank=True, verbose_name='Юр. адрес')),
                ('agent_company', models.CharField(blank=True, max_length=80, verbose_name='Представитель какой компании')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
