# Generated by Django 3.0.7 on 2020-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabinet', '0004_auto_20200611_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Информация проверена?'),
        ),
    ]
