# Generated by Django 3.0.7 on 2020-06-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип топлива')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='type/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Типы топлива',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('props', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('documents', models.FileField(blank=True, upload_to='distributor/docs/')),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
                'verbose_name_plural': 'Дистрибьюторы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='цена за единицу объема/массы', max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='fuel/images/', verbose_name='Изображение')),
                ('density', models.FloatField(default=0, verbose_name='Плотность')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_fuel', to='Home.Distributor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_fuel', to='Home.Category')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Список топлива',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
